// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyiCtOm8W789Ebpk-M70HDulkYbFphGg',
    appId: '1:395308268936:android:4e9eb69d0773b89d0b4e3d',
    messagingSenderId: '395308268936',
    projectId: 'learn-ai-d731c',
    storageBucket: 'learn-ai-d731c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbZCYA4Nez6Crw6P-KdODsgA1PUOoD_k',
    appId: '1:395308268936:ios:d8ce2f8304ebe16c0b4e3d',
    messagingSenderId: '395308268936',
    projectId: 'learn-ai-d731c',
    storageBucket: 'learn-ai-d731c.appspot.com',
    androidClientId: '395308268936-09ae2ksoc3l0r013tr95nj6dnvsm0og5.apps.googleusercontent.com',
    iosClientId: '395308268936-i2kt3i7taf55fsek53j2eu6eluqr8095.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnai',
  );
}
